services:
  - type: web
    name: edusphere
    env: java
    plan: free
    buildCommand: "mvn clean package -DskipTests"
    startCommand: "java -jar target/edusphere-0.0.1-SNAPSHOT.jar"
    envVars:
      - key: SPRING_PROFILES_ACTIVE
        value: prod